### ISSUE TITLE
Table marks are not aligning properly

### ISSUE THREAD

**Issue by ColinKennedy** [OXY2DEV/markview.nvim#75]
**Describe the bug**
The table rendering is off when it contains marked-up character(s)

![image](https://github.com/user-attachments/assets/c6a8dcb7-c24e-426d-922a-6995da2597a5)

**Are you using a distro?**
No

**To Reproduce**
1.  Install `markview.nvim`.
2.  Open a `markdown` document.

```md
| 1 |      2       |                                         3                               |
| - | ------------ | ----------------------------------------------------------------------- |
| n | `<leader>`rr | [r]e-[r]un the last terminal command (The !! syntax is UNIX-specific)   |
| n | `<leader>`st | [s]end to the nearest [t]erminal your system clipboard text.            |
```

**Expected behavior**
The table should have consistent boundaries like here

https://jbt.github.io/markdown-editor/#pdA9C8IwEAbgvb/iiosOEdRVnFxcOikIpdCYnhjIR0mu2EJ/vEe1YF0UfIeEy4XnQmaQ4R32XjUWHSVJDyvoYcj6uY3lD9l86ffMC/bEWz7KPzLwjr1ya1BWGHZlCFzmoUDBS+OAbghGRgLCYLWTBpS3VroK5kdupSnEzpFsQUc4ZYeziDUqfdVq8Xr9lGeI+VggA+QH3aEMyOc5FeOIzjeB3UhoQRldX7wMfB9bWk4/5wE=

Or with [MeanderingProgrammer/markdown.nvim](https://github.com/MeanderingProgrammer/render-markdown.nvim)

![image](https://github.com/user-attachments/assets/084d5a17-884e-4223-acb7-64db01e47c3f)

**Actual behavior**
The table is misaligned

**Neovim version**
0.10.0

**Comment by OXY2DEV** [comment]
![Screenshot_2024-08-05-19-30-16-740_com termux](https://github.com/user-attachments/assets/82deef2c-64e3-4f8e-ab8e-9d5039d3d7f6)

**Comment by davidosomething** [comment]
not quite fixed yet, 
![image](https://github.com/user-attachments/assets/45ef427d-83c1-4256-a32b-35c1daddc0c5)

using commit 9e5275f
file tested: https://raw.githubusercontent.com/davidosomething/dotfiles/dev/README.md

**Comment by OXY2DEV** [comment]
It's only fixed on the dev branch.

![Screenshot_2024-08-05-21-37-47-897_com termux-edit](https://github.com/user-attachments/assets/f858f514-ed0d-46a5-9ead-e76be341f980)

**Comment by davidosomething** [comment]
nice, confirmed!

**Comment by davidosomething** [comment]
might need to re-render the box-drawing lines upon returning to normal mode
e.g. in middle of table hit tab to insert spaces, the
[Screencast_20240806_003430.webm](https://github.com/user-attachments/assets/03bd9c64-a83d-40e7-9d48-93847413b525)
n exit edit mode

**Comment by OXY2DEV** [comment]
That's actually the intended behavior since the goal was to preserve the original width without causing cursor jumps.

Guess I should tweak this behavior a bit.

**Comment by OXY2DEV** [comment]
It should work now.

Input:
![Screenshot_2024-08-06-12-52-38-998_com termux-edit](https://github.com/user-attachments/assets/900c7666-a62d-40c2-aa08-a0a52a31cc66)

Preview:
![Screenshot_2024-08-06-12-52-49-672_com termux-edit](https://github.com/user-attachments/assets/74af0251-2fd1-4ac2-bc7d-8b42b47e96a5)

>[!Note]
> Rows who don't have the correct number of columns are unaffected(so that this doesn't break odd table structures).
> Otherwise, the width is snapped to the separators width.

**Comment by RaidOpe** [comment]
> If you have `wrap` enabled then this could happen.

(https://github.com/neovim/neovim/issues/13474) it fits with `:lua vim.wo.wrap = false` in command mode 🫢

**Comment by RaidOpe** [comment]
> > If you have `wrap` enabled then this could happen.
> 
> ([neovim/neovim#13474](https://github.com/neovim/neovim/issues/13474)) it fits with `:lua vim.wo.wrap = false` in command mode 🫢

But if you don't add '\n' manually, the text of the paragraph becomes very long, which is ultimately not conducive to reading

**Comment by OXY2DEV** [comment]
> Just trying to understand here, why does the table header separator wrap when there is still plenty of space left though?
> 
> ![image](https://private-user-images.githubusercontent.com/3816409/368998898-3a6451b7-5c9c-4647-8367-30b6baf060ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTM1MTYsIm5iZiI6MTcyNjc1MzIxNiwicGF0aCI6Ii8zODE2NDA5LzM2ODk5ODg5OC0zYTY0NTFiNy01YzljLTQ2NDctODM2Ny0zMGI2YmFmMDYwZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMTM0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTljNmYyYWJiOWI1MzExMmEwMjFlOGUzNTRhZTY2NzQ0MjVlYmM5NjZiNGI3YWEzNWMwZjI4OTNjY2RkMjc3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F8mw9llQhxF1Rv2XqsRXtoFDeikoZuaRthSu4he_Mew)
> 
> ![image](https://private-user-images.githubusercontent.com/3816409/368998966-6b41b4db-a088-482b-bce8-705bde4141e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTM1MTYsIm5iZiI6MTcyNjc1MzIxNiwicGF0aCI6Ii8zODE2NDA5LzM2ODk5ODk2Ni02YjQxYjRkYi1hMDg4LTQ4MmItYmNlOC03MDViZGU0MTQxZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMTM0MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM4ZTEwM2JmODc0MDI1NzlmOThmN2RiOTUzYzE1OTI4NmY5ODcxZjMwY2M3Y2RjYzllMGIyOWZkNzc4NmE3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YZpWUv21ltU7_mASnrhs4DOus6Chm3VjqLt1It_ihaQ)

Probably because neovim doesn't take concealed text into account when checking if a line should wrap or not.

So, after adding the borders the line's width becomes twice of its original width which causes neovim to wrap it.

**Comment by l00sed** [comment]
I'm still having issues with table formatting when there is concealed text in the table. Is there a way around this? I believe my markdown syntax is correct... Is there a setting I'm missing? I should be using the latest `main` branch release (24.0.0, I believe). Thanks

| store                                                                                                                                                                                                   | price + core     | CCA  | warranty                  |
|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:-----------------|:-----|:--------------------------|
| [Advance Auto Parts](https://shop.advanceautoparts.com/p/diehard-gold-battery-group-size-24f-750-cca-24f-6/2130001-P?navigationPath=L1*14920%7CL2*15000)                                                | $169.99 + $22.00 | 750  | 3-year free replacement   |
| [AutoZone](https://www.autozone.com/batteries-starting-and-charging/battery/duralast-gold-battery-24f-dlg-group-size-24f-750-cca/832327_0_0)                                                            | $169.99 + $18.00 | 750  | 3-year warranty           |
| [Costco](https://www.costco.com/automotive-batteries.html)                                                                                                                                              | $89.99 + $15.00  | 700  | 3-year limited warranty   |
| [Home Depot](https://www.homedepot.com/p/Exide-SPRINTER-MAX-12-volts-Lead-Acid-6-Cell-24F-Group-Size-750-Cold-Cranking-Amps-BCI-Auto-Battery-SX24F/308488599?)                                          | $99.00 + $15.00  | 750  | 30-month free replacement |
| [O' Reilly Auto Parts](https://www.oreillyauto.com/detail/c/tested-tough-max/marine---boat/battery---automotive/9e0b1d7dae44/motorcraft-tested-tough-max-battery-group-size-24f-24r/mot2/bxt24fa?pos=4) | $134.99 + $18.00 | 700  | 3-year free replacement   |
| [Walmart](https://www.walmart.com/ip/EverStart-Maxx-Lead-Acid-Automotive-Battery-Group-Size-24F/28275657)                                                                                               | $98.76 + ?       | 750  | 3-year free replacement   |

![image](https://github.com/user-attachments/assets/1eea18d6-2b22-4a5e-a5a6-fae6331e186d)

**Comment by OXY2DEV** [comment]
There's a bunch of issue here.

1. You are manually adding spaces which causes the first column to become too big.
2. You need to do \$ instead of $ as it's used for latex blocks(this is from tree-sitter).

**Comment by l00sed** [comment]
I think GitHub might have auto-formatted your second suggestion. Is there a `\` to escape the `$`?

**Comment by l00sed** [comment]
If I eliminate the manually-added spaces and escape the `$`, I'm still getting odd formatting:

```
| store | price + core | CCA | warranty |
|:---|:---|:---|:---|
| [Advance Auto Parts](https://shop.advanceautoparts.com/p/diehard-gold-battery-group-size-24f-750-cca-24f-6/2130001-P?navigationPath=L1*14920%7CL2*15000) | \$169.99 + \$22.00 | 750 | 3-year free replacement |
| [AutoZone](https://www.autozone.com/batteries-starting-and-charging/battery/duralast-gold-battery-24f-dlg-group-size-24f-750-cca/832327_0_0) | \$169.99 + \$18.00 | 750 | 3-year warranty |
| [Costco](https://www.costco.com/automotive-batteries.html) | \$89.99 + \$15.00 | 700 | 3-year limited warranty |
| [Home Depot](https://www.homedepot.com/p/Exide-SPRINTER-MAX-12-volts-Lead-Acid-6-Cell-24F-Group-Size-750-Cold-Cranking-Amps-BCI-Auto-Battery-SX24F/308488599?) | \$99.00 + \$15.00  | 750 | 30-month free replacement |
| [O' Reilly Auto Parts](https://www.oreillyauto.com/detail/c/tested-tough-max/marine---boat/battery---automotive/9e0b1d7dae44/motorcraft-tested-tough-max-battery-group-size-24f-24r/mot2/bxt24fa?pos=4) | \$134.99 + \$18.00 | 700 | 3-year free replacement |
| [Walmart](https://www.walmart.com/ip/EverStart-Maxx-Lead-Acid-Automotive-Battery-Group-Size-24F/28275657) | \$98.76 + ? | 750 | 3-year free replacement |
```

| store | price + core | CCA | warranty |
|:---|:---|:---|:---|
| [Advance Auto Parts](https://shop.advanceautoparts.com/p/diehard-gold-battery-group-size-24f-750-cca-24f-6/2130001-P?navigationPath=L1*14920%7CL2*15000) | \$169.99 + \$22.00 | 750 | 3-year free replacement |
| [AutoZone](https://www.autozone.com/batteries-starting-and-charging/battery/duralast-gold-battery-24f-dlg-group-size-24f-750-cca/832327_0_0) | \$169.99 + \$18.00 | 750 | 3-year warranty |
| [Costco](https://www.costco.com/automotive-batteries.html) | \$89.99 + \$15.00 | 700 | 3-year limited warranty |
| [Home Depot](https://www.homedepot.com/p/Exide-SPRINTER-MAX-12-volts-Lead-Acid-6-Cell-24F-Group-Size-750-Cold-Cranking-Amps-BCI-Auto-Battery-SX24F/308488599?) | \$99.00 + \$15.00  | 750 | 30-month free replacement |
| [O' Reilly Auto Parts](https://www.oreillyauto.com/detail/c/tested-tough-max/marine---boat/battery---automotive/9e0b1d7dae44/motorcraft-tested-tough-max-battery-group-size-24f-24r/mot2/bxt24fa?pos=4) | \$134.99 + \$18.00 | 700 | 3-year free replacement |
| [Walmart](https://www.walmart.com/ip/EverStart-Maxx-Lead-Acid-Automotive-Battery-Group-Size-24F/28275657) | \$98.76 + ? | 750 | 3-year free replacement |

![image](https://github.com/user-attachments/assets/96378c8f-a6db-4a0f-b2e0-532f56d53155)

**Comment by OXY2DEV** [comment]
I think I found the issue.

There seems to be a `%` in the first link that is causing the issue.

This will probably take a while to fix(as it seems to break other stuff one way or another).

**Comment by l00sed** [comment]
Ok, thanks for taking a look. Should I open a new issue?

**Comment by OXY2DEV** [comment]
Turns out, I'm stupid 😑.

**Comment by l00sed** [comment]
Hey, hey, hey! You're a frickin genius, this is a rad plugin that you've dedicated a lot of work to it. Thanks very much for your help.

**Comment by OXY2DEV** [comment]
> Hey, hey, hey! You're a frickin genius, this is a rad plugin that you've dedicated a lot of work to it. Thanks very much for your help.

> Thanks for your kind words 😀. Glad you like the plugin.

Glad that was easy, though ;)

> Unfortunately this will take a while to be added to the main branch(as I am rewriting the plugin, and have only done [55% of work](https://github.com/OXY2DEV/markview.nvim/issues/177). You can try out the `dev` branch if you need the fix immediately. Be warned though configuration has changed a bit.
> You can [see the config for `dev` here](https://github.com/OXY2DEV/markview.nvim/blob/dev/lua/markview/spec.lua#L7)

**Comment by uwla** [comment]
Hi @OXY2DEV

Your plugin rocks but I still get issues with long tables, whose borders are all messed up when the cursor column is greater than the terminal width. When that happens, If I go further left (with `wrap` or `nowrap`), the border messes up.

![MARKVIM 1](https://github.com/user-attachments/assets/cb495651-36ec-46fe-bb99-90f1335c2c2b)
![MARKVIM 2](https://github.com/user-attachments/assets/769d051f-49dc-4a26-9dd7-adcb907949d6)

In such scenario, when the cursor column is greater than the terminal width, I think one solution would be to simply disable the hightlight completely and show raw markdown text.

**Comment by OXY2DEV** [comment]
@uwla Tables no longer render when the start column of the table isn't visible.
